In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('datasets/courses.csv')
df.head(3)

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills,...,Course Short Intro,Weekly study,Premium course,What's include,Rank,Created by,Program,Number of ratings,Price,COURSE CATEGORIES
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
columns = ['Title', 'URL', 'Category', 'Sub-Category', 'Language', 'Instructors', 'Level']
df = df[columns]

df = df.fillna("Not available")
df

,Title,URL,Category,Sub-Category,Language,Instructors,Level
0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,Data Science,Machine Learning,English,"Andrew Ng ,Eddy Shyu ,Aarti Bagul ,Geoff Ladwig ,",Not available
1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Data Science,Data Analysis,English,"Rav Ahuja ,Alex Aklson ,Aije Egwaikhide ,Svetl...",Not available
2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Data Science,Data Analysis,English,"Aije Egwaikhide ,Svetlana Levitan ,Romeo Kienz...",Not available
3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Business,Business Essentials,English,"Rav Ahuja ,Alex Aklson ,",Not available
4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Data Science,Machine Learning,English,"Andrew Ng ,Kian Katanforoosh ,Younes Bensouda ...",Not available
...,...,...,...,...,...,...,...
8087,Certified Scrum Master,https://www.simplilearn.com/certified-scrum-ma...,Not available,Not available,Not available,Not available,Not available
8088,Salesforce Basics Course for Beginners,https://www.simplilearn.com/salesforce-course?...,Not available,Not available,Not available,Not available,Not available
8089,ICP-ACC (ICAgile Certified Agile Coaching) Cer...,https://www.simplilearn.com/certified-agile-co...,Not available,Not available,Not available,Not available,Not available
8090,/irisprodflip456,https://www.simplilearn.com/irisprodflip456?tag=,Not available,Not available,Not available,Not available,Not available
8091,Introduction to Industry 4.0,https://www.simplilearn.com/introduction-indus...,Not available,Not available,Not available,Not available,Not available

In [4]:
import re
def clean_text(text):
    if isinstance(text, str):
        text = text.strip()                     # remove leading/trailing spaces
        text = re.sub(r'\s+', ' ', text)        # replace multiple spaces with one
        text = re.sub(r'[^\w\s:/.\-]', '', text) # remove unwanted characters but keep useful ones like ':', '/', '.', '-', etc.
        return text
    return text

for col in df.columns:
    df[col] = df[col].apply(clean_text)

df = df.drop_duplicates()
df

,Title,URL,Category,Sub-Category,Language,Instructors,Level
0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,Data Science,Machine Learning,English,Andrew Ng Eddy Shyu Aarti Bagul Geoff Ladwig,Not available
1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Data Science,Data Analysis,English,Rav Ahuja Alex Aklson Aije Egwaikhide Svetlana...,Not available
2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Data Science,Data Analysis,English,Aije Egwaikhide Svetlana Levitan Romeo Kienzle...,Not available
3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Business,Business Essentials,English,Rav Ahuja Alex Aklson,Not available
4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Data Science,Machine Learning,English,Andrew Ng Kian Katanforoosh Younes Bensouda Mo...,Not available
...,...,...,...,...,...,...,...
8087,Certified Scrum Master,https://www.simplilearn.com/certified-scrum-ma...,Not available,Not available,Not available,Not available,Not available
8088,Salesforce Basics Course for Beginners,https://www.simplilearn.com/salesforce-coursetag,Not available,Not available,Not available,Not available,Not available
8089,ICP-ACC ICAgile Certified Agile Coaching Certi...,https://www.simplilearn.com/certified-agile-co...,Not available,Not available,Not available,Not available,Not available
8090,/irisprodflip456,https://www.simplilearn.com/irisprodflip456tag,Not available,Not available,Not available,Not available,Not available
8091,Introduction to Industry 4.0,https://www.simplilearn.com/introduction-indus...,Not available,Not available,Not available,Not available,Not available

In [ ]:
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.vectorstores import Chroma
from langchain.schema import Document


df['course_text'] = df['Title'] + " | " + df['Category'] + " | " + df['Sub-Category'] + " | " + df['Instructors']

documents = []

for i, row in df.iterrows():
    text = row['course_text']
    metadata = {
        "title": row['Title'],
        "url": row['URL'],
        "category": row['Category'],
        "sub_category": row['Sub-Category'],
        "language": row['Language'],
        "level": row['Level'],
        "instructors": row['Instructors']
    }
    documents.append(Document(page_content=text, metadata=metadata))

embedding_model = SentenceTransformerEmbeddings(model_name='all-MiniLM-L6-v2')
vectorstore = Chroma(
    embedding_function=embedding_model,
    persist_directory='embeddings',
    collection_name='course_embeddings'
    )
vectorstore.add_documents(documents=documents)

C:\Users\ritam\AppData\Local\Temp\ipykernel_16328\2281088994.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['course_text'] = df['Title'] + " | " + df['Category'] + " | " + df['Sub-Category'] + " | " + df['Instructors']
C:\Users\ritam\AppData\Local\Temp\ipykernel_16328\2281088994.py:23: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = SentenceTransformerEmbeddings(model_name='all-MiniLM-L6-v2')
c:\Users\ritam\OneDrive\Documents\Web Dev\InfoLedge\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\ritam\AppData\Local\Temp\ipykernel_16328\2281088994.py:24: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  vectorstore = Chroma(
c:\Users\ritam\OneDrive\Documents\Web Dev\InfoLedge\venv\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['b07d42f3-0672-4641-8786-fa51e66df769',
 '59a51e21-a30b-4a13-974d-fdae643a9c04',
 '109b72e1-376d-4280-8d73-9d5d7f4054cd',
 '47705a06-90f7-4137-a294-1fbe1d1a5481',
 '8f305039-f27e-4d74-9b10-e6d2288450cf',
 '1ddbc3cc-c27c-4992-a3f9-a8f23a35f587',
 '88fac6dd-1ba3-4806-8dc5-a0ddb76fa787',
 'aa1394c2-63ed-466d-9a9f-dab3d8243761',
 'e909ede8-3268-43b4-b2fb-f718c3ad4f94',
 'b799cd97-8cb4-4b28-831e-bb19bb81841e',
 '0f7f8bb2-97d8-42b3-9466-14ba0d92a72a',
 '31e48db8-7917-423a-ac32-60a053d1a7ed',
 'b461b401-032b-48c0-8e56-b0bf6b26a51d',
 '15ea91ef-fe07-4d8c-b0c9-0215dbf0eff4',
 '94806036-013b-4c50-8e6d-62a885dcc7b6',
 '30c5ebe0-8c34-4404-8fdf-c8ce46f3a4e2',
 'd53b55c0-224b-4b15-b28b-25fb732ca2b9',
 '50023365-286d-41ab-b821-059af0e362cf',
 '33299748-8549-44f2-a48e-8a64ac3de09a',
 '60bceeca-3939-47e0-980e-e0ef31cee72a',
 '58ee1ab8-de09-4657-bd56-0a6b38e227b9',
 '41da6c8a-df83-4911-adc3-bd78b67a5bf2',
 'cbfa49b1-1afc-4473-80cd-852329c6f56f',
 'ee7c166f-37ff-4ce6-9ebb-261e9374a885',
 '897624be-e4ee-419b-abec-97f108d782bf',
 '05c3e20c-c0a8-49b5-92eb-9f015a73aff2',
 '1cb97c1e-1017-48ff-871c-bf594a7a0fec',
 '5c21b71f-e8b5-4d96-9808-8eb360f40ea2',
 'b8e334c6-e6b6-4cd9-97c0-401926b39f67',
 '3543e1c2-d5a7-4221-989c-a67fdd225cdd',
 '4fe2fa3a-544d-4124-94e5-bf6051df694c',
 'aa7c403f-ddbb-4e6e-a9e7-87442e46b851',
 '618d9c52-13fd-40a7-9ad7-43c19d4ab690',
 'a15dc29a-57f9-4f21-bd13-7b35fc3ae4eb',
 '95e8dd16-70a4-4d07-ae45-9f34a4ad3d78',
 '7cad9168-b4d2-4e32-be29-5ba18ff3fd52',
 '71715adf-0790-4822-b8b3-e1588700cdbb',
 '1e514ca7-ac6d-4fed-9d1c-c36be7d4efff',
 '62007267-77d3-46d2-b8fb-c34684dc6872',
 '9bbd95ad-3a40-42dc-ac26-5a7e87bed978',
 '4c5214e2-6b8b-408b-88d9-842518ab75fb',
 '9e1495d1-80b1-482e-bf8a-077a84d5ea1c',
 'edd778fd-5cc0-40bf-b5e9-f13f702c4938',
 'b923031e-75ac-4e53-84fb-d38c6ed49b9f',
 '2f777f38-25a4-4d48-b856-089023baf20e',
 '33f95c29-be5c-48a2-9d00-5fe99eab98fd',
 '82349cca-eefa-4bfd-807d-320d0c486e97',
 'd17d01b5-07d4-4fbd-a4c0-e07e4d3997b6',
 'e705f7d5-a10a-439c-a7c9-c109cd9310f6',
 'f4ff2fc9-b870-4cbd-865f-7473505151ec',
 'c7bd47b6-53fa-476d-9e99-b9c0d6462952',
 'c43ab467-33e4-4c1c-903c-e47c32751026',
 '329d9d51-a6f5-4980-bab5-b6a48b01819f',
 '20fc7576-459d-4240-8c63-af7f6758e26a',
 'bb8a81bb-49bc-4252-8cc0-e519053af68d',
 '9d517208-5892-4dd6-ad95-5c48f614a85f',
 '5f0de7ac-547a-48c9-aa79-e34ecf77846b',
 '431027ff-918b-457e-a4f5-154103439e51',
 'fa88cde7-bbf7-41ca-afc6-23ec38ef8cc2',
 'a92b7984-d7d7-4191-912e-1c462f80ea7b',
 '055d3b03-256f-469d-8cd9-0040ef4776e6',
 '327f59e0-47a2-42be-919f-c9b6f2d60fc9',
 'b03b9ae3-94c4-4b8b-b171-fdd70d13d949',
 '144d886c-eb9f-4190-ab28-8d9e8d666a15',
 '09ac399f-3979-4e5f-8260-656b6c4843d5',
 '7a31b36b-0da2-4398-be1b-55ff1b52468a',
 'd02857a4-f137-4eee-9124-3042287d25ed',
 '7898dcfd-5acf-4154-9e33-e235b6e8af75',
 '1fb6346e-7e0a-4287-af4f-a45513824855',
 '5a2ed00b-6667-42a8-8897-ce63b753756a',
 '7c0c0dfc-1815-48ba-bc18-083d457258a7',
 '69f84d36-a161-404f-b030-35fd5cc073ef',
 'b4ca618a-3025-4811-bfd8-616f7f70ed2a',
 '6ea93a4d-3bae-4ba6-8054-4bde560ffe49',
 '8bd48f2c-53b5-4653-b666-78ebea9ed351',
 '8a6aef03-56ac-4cca-aa7e-34d755a2334f',
 'e98ed2f6-7238-47fd-bd1a-0450bbc2d13d',
 'b59dfc36-f6bf-4875-a408-594e62e75ffe',
 'b0e4b975-3e19-4b28-83fe-982f870f7039',
 '17e1ae89-b206-4d42-8f91-909fe1dcb8ed',
 '155117a9-f0c8-4e68-9106-2b9cbd2ec95f',
 'e7d7ce71-10bf-4488-acec-5fc7493c4481',
 '2341b2aa-5be1-4c9b-b67e-14a051f17a77',
 '22817e29-00d3-4c57-86ba-aae3d00c3606',
 '0454f559-5232-414b-b5fa-ee2f6e4f0a02',
 '5e22eab7-10f7-4743-b251-44654fef22f7',
 'dcc404e1-ae58-4f43-9027-8365af1af177',
 '02c796b6-a2e8-47f9-9cf2-04c0573f8111',
 '0cd25125-9772-49c6-b6ed-a3bd3f07d449',
 'c7d0b755-79bc-40ed-90a6-928237f95248',
 '8e3197b1-728e-4768-9820-97ffb1398f1e',
 'bf967277-960a-42bb-9ccc-f464803f1442',
 '6009296c-5ad6-4cd9-b294-ea03eb877eea',
 'fcadc108-b947-4947-9c0a-4dae38706f83',
 '99ae3d43-8bf7-46e1-96ff-c0298ca8e74a',
 '370d83f2-2e5d-400c-9338-3e520792f9c9',
 '1df1985e-3441-4370-bcdd-7ea7cf336292',
 '6dda640f-c347-49a5-838f-e9ecaf762913',
 '65d35e15-f0ff-464a-be25-5088756d7265',
 'b9c6a944-9945-41cb-b683-15985b25e69c',
 'e14d2860-6ead-46f3-b93b-326b389cff4d',
 'b3cd105c-4114-4336-9d2d-9e59ac88e082',
 'f05fe811-f5f3-4e68-b2cb-367e0821aea1',
 'fb8b2eca-2066-42d8-90d5-19e5820349dd',
 '130fca13-71fa-42ce-8957-e8ea6549af01',
 '6ec70d27-2e81-43d0-a9c5-9c87276820d9',
 'fb4c3709-f9fe-4db3-967e-aa03e41c3ae1',
 '99e1ade3-86f1-4bec-a522-48a2a0c047a4',
 '6f1e9707-0b71-4f57-b04b-ab65781a5af1',
 '044a19bc-c03c-4748-8021-f203a09dbb90',
 '03e6815a-9d12-418e-800f-7ef70a8fbd13',
 '20f232ea-6758-49c2-ae1f-a0b243e94797',
 '0bd77060-0e1e-4a0d-9f28-0a3c8a2ce773',
 '0e6aa3a4-9c20-4b49-8be3-2052b147525f',
 'fd7bd0a9-4188-4265-b175-a44a9058ee52',
 '292671ba-abaf-4a03-9cf3-f16ac676a9c3',
 '1817e54d-42fd-425c-b1a6-7d69d0a72085',
 'dce6d81b-0df9-49ca-af86-34644b1f8cd8',
 '2934cf30-7157-47e0-98e7-8bc60d72bf2c',
 '7c9bbdd1-3577-4063-8829-69e04ee23ce3',
 '7b1f0808-3e8a-451b-8101-d360d911c5be',
 'aa29399b-66e0-4c4a-985f-c36cb7c402a6',
 '267a4e23-9ead-4878-b525-5fe07520c582',
 'eb42ee04-7d7f-40b2-8ccc-56bdc058a48b',
 '3cd9b309-a1e5-44fd-b48e-921fcfc235f9',
 'cc851764-1e55-4aa0-ad94-e42054617717',
 '59c61992-ac31-4cab-8d4c-f683fa57ef25',
 'ab32733e-2e85-4826-8b88-e7d0c0d168c1',
 '4880df4d-a483-49b3-b852-ff288996672f',
 '20344eae-81dc-4361-bd60-2bab68f7d491',
 '9ca4a5b2-8c09-4916-947d-275e1dc58491',
 '606bbcb2-eb3f-4d53-bce0-9738cdd83405',
 'b6da8cac-8a28-44ff-83ff-658f6d550b06',
 '67503014-77c4-4637-bf07-5e0e6c79bea8',
 '867876d7-1cc2-49ae-b053-62916b25abe6',
 '8719009c-1e4d-48bb-843c-6f16f0ad2a2b',
 '9196d691-f639-47ea-aaf5-e835ff04d219',
 'f8df63aa-58ef-45dc-9e57-a6450e25f20d',
 '9ff35cc6-779d-4151-a7a8-294bde4682c1',
 'fc260599-0b3f-4865-a5a8-533cd0446ee4',
 '8ed31a29-8a90-4b22-a643-b46327a3cf9e',
 'ba74ec14-6210-4cdb-a186-d42c4167e9f5',
 'a2207217-622f-4100-a113-53ba128b1eda',
 '6af42a40-eb13-4785-ba2c-d6ee9e9369ce',
 '99603dc4-eb84-4bbc-875d-2ff4b997e17d',
 '508e3ce9-9959-496f-9dc2-423e2fbad36f',
 'c1d1301b-3a03-40e3-ba12-38160ce03b23',
 '12de6c7c-1a9b-4418-ae7c-6fe26ec9f7c9',
 'c05029ca-dae5-4fee-a6bb-bafe486f751d',
 '0bef9b87-1709-4d0e-af8b-3154cfc53f9e',
 '50e0ee2f-8444-4dd4-a43e-985a60bf44df',
 '39946f2a-845c-442b-94a6-8f60a82f2ad7',
 'adff7539-2b14-42aa-8132-599c12b757b6',
 '79e0f4b9-343a-4537-a62e-3c64494a02f0',
 'ee967bdb-00c7-4c41-8fc0-dc6d205942fc',
 '77139404-642f-4581-90a2-e9ea89dfb773',
 '41f6680e-50d7-4015-9d7d-1a5d4c05e7c1',
 'ce6b12b0-d726-4b2f-89b8-253d31f60b23',
 '42279700-f71e-426f-b319-5335f327f9e1',
 '8f32c6ae-7d36-4cd6-80d5-01a96912aab2',
 'c7fac406-f7f1-48f4-8223-19d06c894fe6',
 '0f68068a-c2ac-4832-83ae-7e8906423906',
 '20410b19-fb8d-4767-aa10-301044aecadd',
 '6a049272-76f6-4073-8384-926fbce3c8bf',
 '9cbdef78-96e2-4f56-ad48-488415e65e8e',
 '4397d4d5-4cbe-4915-89c4-0aa625f61f70',
 '34de9f90-d888-4641-879a-67c0feb6026f',
 '7fa0c291-68ef-4e4a-ad47-54e0e0951fd4',
 'd7438b64-f7c0-45db-ae4a-99b4e5da1fa0',
 '23c8e3a3-6160-456d-9b37-7e496e69db1c',
 '5f514c86-8c8f-42ae-b40f-191cb8cc83f8',
 '2bca46ac-51dc-4f44-8fe1-21246deb3a8f',
 '8e574d7e-897c-41b7-9ce4-861bf00bc68b',
 '33b9a850-f0bf-4c71-be18-2929d21ca5cc',
 'ebd46855-2029-478a-9cbf-9775bacad7da',
 '497fdb89-5c07-4b72-b287-357921e5a58e',
 'b0c2030f-d469-4e49-ab48-88079df9e1d5',
 '4183420e-dde2-424c-b2a9-8b98753f5a85',
 '0de160b6-3f37-4e03-bf0a-34524acc5c13',
 '87bb83bb-fcfb-4468-8b1d-cc9c60eb9109',
 '81a7bf90-829e-464d-9f33-f63246f4d36c',
 'acbd68d4-bb34-4c55-b850-5804f298a7e7',
 '0cbf617b-de20-4ead-82ae-11daa372d2ce',
 'b225f2f2-6c21-4f88-b9a7-01c07ec70307',
 '8718b0fe-dfe8-4878-814f-6e0bbb096ae8',
 'ea44da6d-8f98-4e90-b939-8fd20ee78aa7',
 'c76dd517-499b-484d-98e3-8511d17377c4',
 'acbd0a04-0d38-4c93-a950-7a1385da68f1',
 '1fe2231d-c9c3-4a39-a320-5cde91bacc84',
 'efe76965-4def-43f8-8f64-57a827cd73c1',
 '9f96ef20-2e73-470f-aac6-4d8570dfa73f',
 '1ebe5f0d-39a0-4f94-a95d-4dd366b9c552',
 '8dd1d815-c354-4643-977a-4e6b77506f97',
 '2b654a15-f0b6-4fd4-8cc3-0d9535e8f1c0',
 '04cc7482-1e03-4eee-9deb-aa7de5595f3f',
 '3bea7d24-e81b-48cb-9c5f-cd651e3cdf99',
 '7398f169-6f13-406e-b5f5-29340036dbf0',
 '620910ac-b1b9-4637-acc4-86cfd0f3f7f4',
 '33d2413a-07a6-4864-b7c2-10f7adb9dfd6',
 'fb3a46d2-6a6e-41ca-997c-1645452fe8b5',
 '57727ab2-1eb0-4ca7-bbb9-afffe6684297',
 '3b195d98-e7c9-4fc2-8daf-8ed5969a8ae5',
 '190bab49-f45e-4932-8e45-5fc5b9e224ef',
 '5e765bec-a5eb-4e5d-88c0-75f286fbe357',
 '228db7b5-5b17-462c-93a6-9c80dd6e24c8',
 '45909ba5-ffb6-4038-8cfd-85a004f132f0',
 '403e184a-b200-4ebc-b558-6a0970187e8e',
 '2fe050a5-e66e-47e3-9d71-cdb1e359cafc',
 '07ab23b4-2911-4830-b66d-6596cc3534bc',
 '16c01207-140d-4010-a805-951a6f0c93c9',
 '7ba59676-aaf3-4569-9cea-ebe095b45399',
 '31bcb661-77ed-424f-9eba-74fc4968cd55',
 '72c5241e-6d85-44a2-9d57-bb68bf53602d',
 '1f8e69ed-ad0f-4a75-9bac-6862f8c70395',
 'e48e2f38-5e1f-49a6-bdad-2399ecc1dc1d',
 '1988893c-476f-441b-89d4-36167de0aef5',
 '8ee69abc-2504-4783-bf84-328c771567d6',
 '85f43c18-1b26-4ab8-a682-a63fd13f9642',
 'c1941dc6-4bad-405b-851d-33fdd7450066',
 '7cb9e314-5488-4305-b3ee-9e1cddec0122',
 '53fd90d0-7509-4574-9eaa-7426036e7db9',
 'd9b23915-ba4c-411f-9614-86dbcf75a66c',
 'd0a5fa96-c66a-49eb-a1f8-7a6ef209f358',
 'f7c3fdc2-909a-41ee-9e30-ca9c2bc29930',
 'df930bae-a29d-4d44-abd5-1688e866989f',
 '245f08b9-9090-4c83-9ea2-4680eeb09abe',
 'e101b391-1c67-43b5-8d61-f24eac9b3060',
 'c91af653-8e12-4478-aae2-f3302edb8862',
 '948885b3-e1e7-41f5-a0ee-b140626e67d6',
 '5204ffac-086a-4f12-b701-f8e7da6d23b6',
 'd75dbc30-612c-4b51-9a58-312d7601024b',
 '4e9aa97f-bf5c-483d-ad92-98e1f8f9ac26',
 '020db0d6-eb63-421e-9e50-aaeae8428bab',
 'fa414dcf-4f0b-49b7-9eae-17bda32aae8a',
 '4bd89e9c-f834-453c-9b93-d98764199b35',
 '795dac27-6221-471d-8869-211968b70124',
 'b3969caf-5f77-4cb9-82b9-95d93a8b8a04',
 '840c3d99-f17c-479b-92b2-f981ce7ffc27',
 'f97de5d6-e8d0-4de3-a963-0ebaab38e714',
 '89d4e22d-4406-4f56-a6c2-6ef5750f0a15',
 'c53c08e6-51dc-4e82-8e8b-f39765cb90d0',
 '40fb7313-add4-4d35-a726-cb1bb9b00554',
 'ef3df4a8-b5fe-4e5d-8625-398fec2efe7c',
 'fb9b6d9e-e7fa-4687-bac7-49ff4a68ae73',
 'fd231d50-4715-4e46-930e-3eb49f5323ee',
 'f6c277ef-23f9-420f-bc60-4831c44294fb',
 '5afab3dc-ce03-470e-9bdf-6287a25d43ab',
 'b827254c-4c4d-4da1-bc38-deca347316ef',
 '408ff002-51fd-473c-8fb3-4aca8fbd795c',
 '2ee39dfb-67c4-43af-ab11-3cb7984545a3',
 '823ee0b4-5894-4f19-9d34-63919b24c47e',
 '8ee3d51b-8183-45fb-88d6-adde36fd4e35',
 '6436f990-8eb3-489b-b89f-c837007ab6da',
 '4cb3a36c-ae21-46ff-841c-95aa9d20920a',
 '2c9ce2d2-609d-46f7-9726-fefecb1d8fa3',
 '099ceb96-7f4d-4f11-98c7-9b26edacd6cd',
 '9e0f1707-ecd1-4b3e-8cdc-947ea7a2299c',
 '5029d64b-c328-4f9d-9929-1d572f940e4e',
 '88565d8b-5e26-4573-bbf8-0f50229fdf6c',
 'b555daea-0120-4736-8a94-8267db1260b8',
 'a59a54f7-7604-46cd-ab3f-9702061955fd',
 '7a909fae-5fd2-4420-b339-a1efa45601f8',
 'a873a9e3-3532-4e6f-a97e-dcc9e485aea4',
 '1017ec0c-18c3-46c4-878b-e2f246ea5c41',
 '47e86f27-ac6f-4a59-bf72-307414f60185',
 '03714d66-c9f9-40b1-94a4-030d58d1a9f9',
 '951505bb-23de-43cf-92c4-7dc36c03e60e',
 'd3838aff-7811-4f67-aa97-726a194d05e2',
 'bbb9fd19-1e92-4020-a913-75f82b993dc6',
 '37c20405-cfba-4856-b408-8ab9f4cd1fd5',
 '70569fe5-e1f5-4ab8-8886-9a6fdcf039b4',
 'ebc7384a-f74c-4d64-95f8-33fbc240e017',
 '9cbeda9e-f428-45e6-86b4-8822e569bebe',
 '32f5d36e-d252-4ecf-899f-f1c91c68aef6',
 '5574a67b-97ea-4d54-861f-514b6947041b',
 '8127c0b5-ee78-4995-bc4d-3bcded66c036',
 'ab93b9e4-d910-40a5-ae46-5e9095b5f693',
 'f78a366c-2b59-477e-9dd0-a5e228a8cb06',
 '55f6041f-0a59-4910-9b3c-1b4e3d031130',
 'fc74f966-be7c-4ae1-80d6-c589f6e3388f',
 'c3bc5ca2-2d94-439f-a599-636430512b8d',
 '0a18686d-3dda-4798-9cb1-95151dc8597a',
 '9ecf6d94-faeb-4862-9238-6340e2b9f9e7',
 '7642b29f-8af0-47bc-b9d0-da799aae3913',
 '32576e3c-1433-47ee-8b63-2a2c0dc27768',
 'acfe8d64-2e24-4144-8cdb-9b731bb3dd0a',
 '24cb0c45-7dcd-4677-8199-87184b0dabbe',
 '44c1476d-9605-465a-a1a0-8598c8d991b9',
 '01614ebf-837e-4590-bdc8-738b5daf0ad3',
 '721aa128-2c4f-4bf7-bcf7-283f1f27f26f',
 'bd408979-a386-423b-ad2d-6911e8944bc5',
 '332530f1-b66e-4044-b226-911bf2559541',
 'a8d78b34-642e-426d-bf1c-f24a5a00b883',
 '74e92724-d03b-452f-b170-17fbddeafdd1',
 '37397679-304d-4ece-869a-7e4484ee64fc',
 '652d0530-566e-41de-a785-23309e6804b2',
 'bdaedddf-4921-4999-a9d9-a194d47d418f',
 '79ed867b-3ce4-452f-839f-e481c10c04b8',
 'dd004c6e-becf-46f0-a94e-12f2215c2abc',
 'db9fadf2-60cc-4fe8-9fcb-3e2e2389ff73',
 'bde2e06d-6bb7-43c0-85e7-1766b2520dbe',
 '0c9c78e2-008e-4f99-9a98-bf903a2a3414',
 'dca35ce9-8227-478c-9f14-310b7efb7016',
 '70836d3a-5d8b-492a-a53d-57f488967738',
 'b114b90a-9f92-4fee-8c18-69220c608b1f',
 '4ed97d55-4887-4712-b61d-bd047b6943fc',
 '43af1e16-3d62-446b-b63a-f0b4026d4493',
 '8bf1e998-e386-4555-86f4-e3d6b5e67be2',
 '3e200da7-014d-4bc9-b542-044fc93ef802',
 '53ef8d42-df99-42e6-a4b2-13d7978e5e6c',
 '7658b321-6b00-4048-8575-521e7bc068da',
 '1e6487e7-dd03-44ca-8cf9-be528808d3c3',
 '859fb6ec-dcd8-443d-95e6-7de014713777',
 '867efa1a-9419-4bc9-aaeb-dc3cd1edc6d0',
 'a0071aac-61bc-4fc2-8fd6-ca6b5593c5d2',
 'bb448456-3137-4e35-9b20-023c76164c02',
 'ce907798-6e47-42e7-b277-95c0123504f7',
 '6e2503ce-6701-4fa3-aae9-4493345ea03d',
 'bb5afd66-6ad0-4779-8388-ab5b849a78c9',
 '1856d6e8-20a4-4778-b4c2-97cde5873fda',
 '24c958d5-4276-45de-b57b-7fb6c35719c9',
 '0f532eda-cc86-4e31-b0fd-b4e652fa9675',
 'bfb88ab4-47eb-41fd-87ab-012ebe7ba903',
 '020e1d65-8060-46e4-8197-e640d5353b11',
 'b242ac17-f404-4605-9367-4b2b9393eb94',
 '34474d48-909a-4753-9d22-cc2ce6d13f1f',
 'ae4b7e0d-0abc-4f0a-b196-3b8020952928',
 '5e834136-4e74-4bd2-8ca2-2dc943ca2482',
 '31ff30b5-b3cd-41eb-91ee-24786b5a209e',
 '67b99c06-2409-4649-ba37-a5dae9bff6e0',
 '63515f87-81c0-4859-b205-4028679b5a16',
 '1745701e-2ffb-4afe-a5e2-3a8f6712eca2',
 '399ae93c-f49a-4c6b-9b71-f1e90454edc3',
 '60f435f3-a604-4b81-ab40-d1f43ef17822',
 'ae91d3e8-40ae-4d41-bb23-d7f04e8ec1c0',
 '5a35c58b-2a84-4290-9756-b45ad819fb37',
 '41128d19-5f89-4070-88dc-f1014082f5e7',
 '027f803f-f10b-4fe7-8ac7-9bbf09cc7e0c',
 'e7a84e01-76ae-4bb9-99ec-98afde5475bf',
 '4293c1fb-5c53-46e8-a9be-7d59c12423ba',
 '445f201a-294c-4c02-bc23-26d72cafc446',
 '410dc175-22cd-460f-a8cd-bbf766e5760d',
 '503614ff-01de-4bb7-b7c6-4cdc52f42c68',
 'dc7c1276-cf53-43a7-a749-233a7c92f80b',
 'aeca92d8-2a62-4cb6-ac2f-9390e7356750',
 'c72e828a-a156-40bb-a693-9d1c0d54cf5a',
 '8866d901-9fb4-477d-9a88-255a41a9f1f3',
 'bfee494c-209e-4edc-b15d-0238c39fb0d7',
 '8dd9b652-0c56-4ac5-93c2-188269687a1f',
 'b36057e4-157d-45fb-85eb-307796904c25',
 'eae25654-1515-432d-b703-f165a6a02c6f',
 '878bcad6-6f34-494b-9989-1ab90a00558e',
 'edaab0ca-945f-413c-9621-2bc31092e2ad',
 '076af318-afb2-4df3-860d-9079e9902ed4',
 'fa0f67f3-33ab-4cb9-883b-640a4a9e378b',
 '229ddf31-fd0b-4ae6-a968-59b539bb6e8f',
 '6cc07952-a5e3-4b0b-ac29-3042d26bfefa',
 'e17f2e0b-939e-4270-a180-03e11bfe648e',
 '70332d56-a4bc-42cf-a8b5-434fcf07828f',
 '7855aa1f-a61f-4714-89a4-817ddde86fa8',
 'ca2ec533-f593-4d8b-942b-6c3338adbfde',
 '2652af52-1d52-4d8b-b1aa-9cd9df871849',
 '289b9fd7-93fa-43a1-b824-6bd6f02d9ec3',
 '34d5a74a-32a1-4da5-9e67-1d34dcae31f4',
 '147aad18-0cc3-462c-a13b-5e798a77b77e',
 '3816a9c5-b17a-4262-b808-7a12c5da1f6b',
 '7bdbd974-39d1-4454-b52f-5759a7c186c9',
 '06949b01-3432-4cf0-b0bf-ff283068bb7c',
 '1007516a-4126-4287-bd2e-0f38f9565e9c',
 '633dfebb-42a6-499f-ba39-68a2b2ecd60b',
 'f02e51c6-4120-409c-afc1-83a19f82bc48',
 '037f1ea8-b796-470b-8b83-8ee6d69c5296',
 '40c5b653-1910-4c79-82c0-a07b3865686a',
 '85bfc415-fd5d-4794-98d1-211107b8fc9a',
 '7218e36f-3068-484a-9bcc-6b7cb39b1c70',
 'fd099327-9862-40ae-b4fb-848e50eb7863',
 '4d1bb57a-9644-4b23-9025-a56c56db7410',
 '5a97859f-2213-4623-b7f2-3d308ae31248',
 '53e7dfcc-a6cc-41f1-8741-0beaf94823a3',
 'bcee1bd8-42ec-4a8e-813f-35aa41099b52',
 'b1c0af58-cb85-46eb-b31e-67694edc2621',
 '2007b465-3ee8-4949-abd9-22a40272d2ea',
 'bd39e5ec-b0d2-4cc2-999f-c290154be078',
 '0afec674-489c-4415-8bd1-bd362399fa25',
 '0eab944e-c2fa-4f60-8810-95a4f2dc1924',
 '6c7a5557-c562-4375-9ab6-c3d24bd501f9',
 'b2880bb6-2684-49e8-adb3-fcd8663f5999',
 '2f86e109-5121-43bb-a6b0-c3370612ddbc',
 '06ffe9d2-74de-4a60-87b6-7c576a8b4070',
 '8035bb81-b8fd-4852-bbb5-4d9c3c8d7f96',
 'b46400e8-0759-4289-a4fb-ee23331f975d',
 '18e497b2-706e-4d93-851b-4ea7d74a42d8',
 '72e1e3c6-e7a7-4447-9a57-a71705562ce1',
 'd002fc30-20fa-41ce-af0f-3ed37cd076b0',
 'fd8bcb34-5086-483b-8428-8fd8a5f5c0a0',
 '1a136b62-4a7b-4f82-afd8-f0a6de7d2454',
 '6d5449ae-8eb8-4dc4-a53f-4b4336cb5705',
 '3023dc73-2cd1-4c37-8052-97153cb2f3aa',
 '035e6e78-455b-401a-817a-4abdc03c59c7',
 '8b9c2404-f132-47e3-a1a8-65346143ccb5',
 '801a6ee1-ca21-474e-9de6-919f5dc1d7fb',
 '609dcdcf-b4a4-4c84-8056-f7af968e3165',
 'c4ecaf10-2326-42cc-8b98-8b5e82baff56',
 '91f2e4af-0eed-4ccd-8b06-74b059881bf3',
 '4d50ea10-129c-4160-8c43-af6ace0169aa',
 'fad779f0-cc73-4b02-955f-a9f082e219a0',
 'c97f79ee-060b-490b-824f-531f237972dd',
 '0806e3dd-217f-4314-8b4a-bab80491c484',
 '9e0a1704-9840-455f-a93d-c30b9cac65cf',
 '630c3af3-9806-4283-8d98-65844e15e8b9',
 'da558e2a-023e-4498-b73a-7141adac61e1',
 'f32b039d-e2f2-41fa-99f5-114254422ff5',
 'f935b3d4-5678-41c5-bc74-e5e9d64ca236',
 '16c5a635-94a1-44fa-b01e-bfe38e6806ab',
 'b6658a6e-5b55-429b-818e-60da7ac37d55',
 '5008e2e4-59e5-4665-8b4b-2092c3dd095c',
 'efba2ee6-a077-4407-a622-f0adc759d621',
 '8ed28fd5-02d6-46a5-9355-f009e05b24a6',
 '21c01be0-8f02-4749-b751-06e8c2258295',
 '720e8924-404a-45a5-89e7-00949281b5ed',
 'b60b86b0-e4f8-4afd-b1b9-c7fd6f9f5687',
 '2be94785-4e01-409e-be60-52ff60239f33',
 'e9ec5aa6-fc2d-4e2a-b1a7-95ef5cdcabc0',
 '40db05b8-0bc2-41ef-88aa-417d5cc5a0a3',
 'be4764de-7cf7-4d57-b75a-5cdec8aefb2a',
 'd62784b3-082d-46f8-8bb4-4e18b696b190',
 '3337a67a-3042-45b2-b952-b2476abee9bc',
 '51c0e236-8d45-41ce-88e8-7ca49096aace',
 '5a0ffaf2-c0a6-4cce-8e0a-35ccd48363b0',
 'ee972500-671d-48fb-b9fe-b3ecfde9e656',
 '23a14be0-64e0-4fab-bfbf-8e0466227400',
 '0082aaa7-a818-4eda-be6f-ec46b5756ba6',
 'd5055c71-c1d2-4d21-b85f-0ed4f75bf0f5',
 '558f2ed0-975d-4ecc-b26d-4cb0a70f28dd',
 '011ebd77-23b5-4c8c-8ad5-092e344380eb',
 'ebd5f8ab-2108-4574-a597-485a1e9cffa2',
 '6248cdbb-f186-43d7-870b-8eb550805067',
 '8a1799a5-7a89-454f-ae69-183309d95695',
 '6f4e65af-8561-4cee-85f5-4704da917333',
 'a96545fc-c9fe-4068-891f-768d1f118ce0',
 '9a5d0f62-2b09-45ad-aefb-7c5049d61e79',
 '5b1288a1-6acc-43d4-9e6a-336f717a0eb3',
 'da1377ac-b15c-4c87-a84f-98e65f7a6f5f',
 '2431319e-0376-4aff-89a8-a22c1e2554e9',
 'ce8fc7eb-8668-48de-9990-2dffbc755e29',
 '95cb63ce-2710-4c2f-bcdc-9f7f7c8ba293',
 '5d2dcc0a-bfaf-4e9c-a578-7e03c8eb5aa3',
 'f12026ec-3d94-49ac-8688-963b24e2d814',
 '5ec47440-7907-4c0c-be50-2001ed4e1713',
 '6202f672-7aa3-4b92-8271-67bc9f907976',
 'a732fc06-7511-47e0-8fd9-87709630b08c',
 '3aa28628-10b7-441d-ad59-ebcf29c144fb',
 '69b5ca4c-43d9-469d-8e99-8e668905b191',
 '9dd484df-7358-407b-8ba9-5673e30ec83d',
 '33210099-2fa8-49d8-aedd-858809e5ec56',
 'f30ee186-c249-478a-9fc8-bfc011b8f2ac',
 '39268745-1d6c-4aa0-b843-318f42943523',
 '785cc83a-4f32-468a-8c92-6859fa10ee8d',
 '3c2e37e7-cf26-46a1-aebe-c1f04bfce019',
 '82ba8746-1380-46d5-9cf6-a15b1fae7627',
 '3104710a-b9ce-4481-b653-504d9250255b',
 '265d74bd-b19d-4fa9-92b3-32886f3f27cd',
 'caa0fbb0-610d-4ecf-a573-e1e379496be2',
 '84779699-8ca4-4893-87ba-c03533a7c33d',
 '1bee187a-c5c3-438b-b43b-d498d22675a4',
 '3fd1761a-5d4e-4db4-939a-bfa0886d8ab9',
 '2bae067d-d421-4ff8-85ac-64e667396484',
 '9533b48d-143b-46db-aaaf-7de753dd1d98',
 '7206959e-ae9a-42e2-b81a-db9fd733dd5b',
 'f05eb1ed-0656-42fb-9b54-dd37c980f2be',
 'aeac614f-b5ea-4cf0-be1c-ca3d448a7e4d',
 '8478cc2a-1bcf-4d49-a680-6bc9372df192',
 '10e0078d-1d99-4908-88c0-1a2a8ea97239',
 '37fa1fa6-bce0-4ccf-9f1f-c192b06920b4',
 'c06feb98-83de-48be-88cc-92fef95f6438',
 '5e681e84-5a7e-49cd-a094-99a71b4d672f',
 'd40a2560-6b32-4929-8ff4-a82f87de2974',
 '5ec1a3ad-246e-4add-a160-371011d54e3f',
 '6faf0986-ed29-427e-9fd2-fab4095e87ae',
 '19e54970-5dfb-472b-a044-5fa8b8cc300d',
 'bf22d5c5-c2f6-4fd2-ad6a-1d092a96b8aa',
 '593e1aef-1c47-4482-bee9-1816f49cc1b8',
 '7f00065e-6299-47c5-9e01-33519d0e506f',
 '237a4268-4fa2-4405-98ac-df85eb853bec',
 '50dccecc-f5f2-4725-a3f8-5682d580afa8',
 '31fcbf0a-d386-4059-aad8-a88bfcfab22c',
 '216d23c5-4d0e-4b33-a8fa-b95489441bb9',

In [3]:
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.vectorstores import Chroma

embedding_model = SentenceTransformerEmbeddings(model_name='all-MiniLM-L6-v2')
vectorstore = Chroma(
    embedding_function=embedding_model,
    persist_directory='embeddings',
    collection_name='course_embeddings'
    )
vectorstore.similarity_search(
    query='Some beginner level courses on Mongodb',
    k=10
)

[Document(metadata={'language': 'Not available', 'sub_category': 'Not available', 'instructors': 'Not available', 'category': 'Not available', 'url': 'https://www.udacity.com/course/data-wrangling-with-mongodb--ud032', 'level': 'Intermediate', 'title': 'Data Wrangling with MongoDB'}, page_content='Data Wrangling with MongoDB | Not available | Not available | Not available'),
 Document(metadata={'level': 'Not available', 'sub_category': 'Data Management', 'instructors': 'Rav Ahuja', 'language': 'English', 'url': 'https://www.coursera.org/learn/introduction-to-nosql-databasesspecializationnosql-big-data-and-spark-foundations', 'category': 'Information Technology', 'title': 'Introduction to NoSQL Databases'}, page_content='Introduction to NoSQL Databases | Information Technology | Data Management | Rav Ahuja'),
 Document(metadata={'title': 'Database Management Essentials', 'level': 'Not available', 'language': 'English', 'instructors': 'Michael Mannino', 'url': 'https://www.coursera.org/learn/database-managementspecializationdata-warehousing', 'category': 'Computer Science', 'sub_category': 'Software Development'}, page_content='Database Management Essentials | Computer Science | Software Development | Michael Mannino'),
 Document(metadata={'url': 'https://www.coursera.org/learn/database-applications-phpspecializationweb-applications', 'instructors': 'Charles Russell Severance', 'title': 'Building Database Applications in PHP', 'sub_category': 'Mobile and Web Development', 'level': 'Not available', 'language': 'English', 'category': 'Computer Science'}, page_content='Building Database Applications in PHP | Computer Science | Mobile and Web Development | Charles Russell Severance'),
 Document(metadata={'url': 'https://www.simplilearn.com/salesforce-coursetag', 'instructors': 'Not available', 'sub_category': 'Not available', 'title': 'Salesforce Basics Course for Beginners', 'language': 'Not available', 'category': 'Not available', 'level': 'Not available'}, page_content='Salesforce Basics Course for Beginners | Not available | Not available | Not available'),
 Document(metadata={'title': 'Data Collection and Processing with Python', 'sub_category': 'Software Development', 'url': 'https://www.coursera.org/learn/data-collection-processing-pythonspecializationpython-3-programming', 'instructors': 'Paul Resnick', 'language': 'English', 'level': 'Not available', 'category': 'Computer Science'}, page_content='Data Collection and Processing with Python | Computer Science | Software Development | Paul Resnick'),
 Document(metadata={'url': 'https://www.coursera.org/learn/introduction-to-relational-databasesspecializationdata-engineering-foundations', 'language': 'English', 'category': 'Information Technology', 'level': 'Not available', 'instructors': 'Rav Ahuja', 'title': 'Introduction to Relational Databases RDBMS', 'sub_category': 'Data Management'}, page_content='Introduction to Relational Databases RDBMS | Information Technology | Data Management | Rav Ahuja'),
 Document(metadata={'instructors': 'Rav Ahuja Ramesh Sannareddy Steve Ryan Karthik Muthuraman Aije Egwaikhide Romeo Kienzler ', 'level': 'Not available', 'url': 'https://www.coursera.org/specializations/nosql-big-data-and-spark-foundations', 'title': 'NoSQL Big Data and Spark Foundations Specialization', 'language': 'English', 'sub_category': 'Data Management', 'category': 'Information Technology'}, page_content='NoSQL Big Data and Spark Foundations Specialization | Information Technology | Data Management | Rav Ahuja Ramesh Sannareddy Steve Ryan Karthik Muthuraman Aije Egwaikhide Romeo Kienzler '),
 Document(metadata={'title': 'Oracle Database Foundations', 'category': 'Computer Science', 'language': 'English', 'level': 'Not available', 'sub_category': 'Software Development', 'url': 'https://www.coursera.org/learn/introduction-to-oracle-sqlspecializationoracle-sql-databases', 'instructors': 'Rafiq Wayani'}, page_content='Oracle Database Foundations | Computer Science | Software Development | Rafiq Wayani'),
 Document(metadata={'language': 'English', 'category': 'Data Science', 'title': 'Get Started with Python', 'instructors': 'Google Career Certificates', 'sub_category': 'Data Analysis', 'url': 'https://www.coursera.org/learn/get-started-with-python', 'level': 'Not available'}, page_content='Get Started with Python | Data Science | Data Analysis | Google Career Certificates')]

In [19]:
results = vectorstore.similarity_search_with_score(
    query='Some beginner level courses on SQL',
    k=10
)
for doc in results:
    print(f"Title: {doc[0].metadata['title']}")
    print(f"Category: {doc[0].metadata['category']}")
    print(f"URL: {doc[0].metadata['url']}")
    print("---")

Title: Oracle SQL Basics
Category: Computer Science
URL: https://www.coursera.org/learn/oracle-sql-basicsspecializationoracle-sql-databases
---
Title: Learn SQL Basics for Data Science Specialization
Category: Data Science
URL: https://www.coursera.org/specializations/learn-sql-basics-data-science
---
Title: Oracle SQL Proficiency
Category: Computer Science
URL: https://www.coursera.org/learn/oracle-sql-proficiencyspecializationoracle-sql-databases
---
Title: SQL for Data Science
Category: Data Science
URL: https://www.coursera.org/learn/sql-for-data-science
---
Title: SQL for Data Science
Category: Data Science
URL: https://www.coursera.org/learn/sql-for-data-sciencespecializationlearn-sql-basics-data-science
---
Title: Introduction to Structured Query Language SQL
Category: Computer Science
URL: https://www.coursera.org/learn/intro-sqlspecializationweb-applications
---
Title: Databases and SQL for Data Science with Python
Category: Data Science
URL: https://www.coursera.org/learn/sql-data-science
---
Title: Databases and SQL for Data Science with Python
Category: Data Science
URL: https://www.coursera.org/learn/sql-data-sciencespecializationdata-engineering-foundations
---
Title: Databases and SQL for Data Science with Python
Category: Data Science
URL: https://www.coursera.org/learn/sql-data-sciencespecializationbi-foundations-sql-etl-data-warehouse
---
Title: Databases and SQL for Data Science with Python
Category: Data Science
URL: https://www.coursera.org/learn/sql-data-sciencespecializationdata-science-fundamentals-python-sql
---

In [ ]:
import torch

: